### ISSUE TITLE
README could use some more content

### ISSUE THREAD

**Issue by devinrhode2** [CrowdStrike/faltest#244]
I am mostly curious if this project uses webdriver

In the readme it doesn't explain too much about this project, I don't know why I would use this project over others.

**Comment by kellyselden** [comment]
The section you're looking for is in https://github.com/CrowdStrike/faltest/blob/master/CONTRIBUTING.md#tech-stack.

Closing as a duplicate of #26, but I agree the docs could use a revamp.
