### ISSUE TITLE
Provide insight when exceptions happen

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/faltest#299]
For example, on emberclear, I get the following output:

link: https://github.com/NullVoxPopuli/emberclear/pull/279/checks?check_run_id=641002972

```
 1) chat
       New users can add each other and then communicate
         fresh users can begin communicating with each other:
     waitForInsert: waitForInsert([data-clipboard-text]): waitUntil condition timed out after 30000ms
      at Browser.waitForExist [as waitForInsert] (node_modules/@faltest/browser/index.js:321:15)
```

This really doesn't tell me anything. It'd be great to know the current state of the browser / dom / screenshots or whatever so that the C.I. log is useful.

**Comment by kellyselden** [comment]
Fixed via #318
