### ISSUE TITLE
Can wdio.conf.js files be used with faltest?

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/faltest#324]
I'm looking at configuring webdriver, and noticed they use configuration files.

https://webdriver.io/docs/browserstack-service.html

does faltest do anything to prevent the use of those? I know there is a lot of scripted config setup

**Comment by kellyselden** [comment]
No. We don't use their test runner (which is what their config drives), only their js libraries. We'd have to reimplement their plugin lifecycle hooks to be able to use them.
